# Generated by Django 6.1 on 2026-08-16 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='cover_image',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
