# Generated by Django 6.1 on 2026-08-16 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_product_cover_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='screenshots',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
