import stripe
from celery import shared_task
from django.conf import settings
from django.db import transaction
from django.core.exceptions import ObjectDoesNotExist
from .models import Order, OrderItem, Product, DigitalKey, UserLibrary
from users.models import User

# In production, this would be set in an environment variable
stripe.api_key = getattr(settings, 'STRIPE_SECRET_KEY', 'sk_test_mock')

@shared_task(bind=True, max_retries=3)
def process_checkout_task(self, user_id, product_id, stripe_token, idempotency_key):
    """
    Celery task to handle the entire checkout pipeline securely.
    Executes in the background via Redis to ensure the UI doesn't freeze.
    """
    try:
        user = User.objects.get(id=user_id)
        product = Product.objects.get(id=product_id)
        
        # =====================================================================
        # 1. OPTIMISTIC CONCURRENCY CONTROL (OCC)
        # =====================================================================
        # We loop to try and claim an available key. If multiple users try to buy the 
        # same game at the exact same millisecond (e.g., during a flash sale), 
        # the DB versioning prevents them from claiming the exact same key.
        max_attempts = 5
        claimed_key = None
        
        for attempt in range(max_attempts):
            try:
                # Find the first available key for this product
                available_key = DigitalKey.objects.filter(
                    product=product, 
                    is_claimed=False
                ).first()
                
                if not available_key:
                    return {"status": "failed", "error": "Out of stock. No digital keys available."}
                
                # The OCC check: We only update if the version hasn't changed since we read it
                current_version = available_key.version
                updated = DigitalKey.objects.filter(
                    id=available_key.id, 
                    version=current_version
                ).update(
                    is_claimed=True,
                    version=current_version + 1
                )
                
                if updated:
                    claimed_key = available_key
                    break  # Success! We claimed the key securely.
                else:
                    # Someone else claimed it in the last millisecond. Try again.
                    continue
                    
            except Exception as e:
                return {"status": "failed", "error": f"Database error during OCC: {str(e)}"}
                
        if not claimed_key:
            return {"status": "failed", "error": "High traffic. Could not claim a key. Please try again."}

        # =====================================================================
        # 2. STRIPE IDEMPOTENCY KEY LOGIC
        # =====================================================================
        # We pass the idempotency_key generated by the frontend. If the Stripe API times out, 
        # or if this Celery worker crashes and retries this exact task, Stripe will recognize 
        # the idempotency_key and return the original successful charge instead of double-charging.
        try:
            charge = stripe.Charge.create(
                amount=int(product.price * 100),  # Stripe expects cents
                currency='usd',
                source=stripe_token,
                description=f"Purchase of {product.title}",
                idempotency_key=idempotency_key  # CRITICAL: Prevents double-charges
            )
        except stripe.error.StripeError as e:
            # If the payment fails (e.g., card declined), we MUST release the key back to the pool
            DigitalKey.objects.filter(id=claimed_key.id).update(is_claimed=False)
            return {"status": "failed", "error": f"Payment failed: {str(e)}"}
        except Exception as e:
            # If the request times out, Celery's 'retry' will catch it. 
            # We raise self.retry(), which queues it up to run again in 5 seconds. 
            # Thanks to the Idempotency Key, the retry won't charge the credit card again!
            # Note: We do NOT release the key here, because the retry will need it.
            # If we max out retries, a separate cleanup job would need to release orphaned keys.
            raise self.retry(exc=e, countdown=5)

        # =====================================================================
        # 3. CREATE ORDER & ASSIGN TO USER LIBRARY
        # =====================================================================
        with transaction.atomic():
            # Record the financial transaction
            order = Order.objects.create(
                user=user,
                total_amount=product.price,
                stripe_charge_id=charge.id
            )
            OrderItem.objects.create(
                order=order,
                product=product,
                price_at_purchase=product.price
            )
            
            # Securely assign the claimed key to the user's library.
            # The 'key_code' remains encrypted in the database at all times via our EncryptedCharField.
            UserLibrary.objects.create(
                user=user,
                product=product,
                digital_key=claimed_key
            )
            
        return {"status": "success", "order_id": str(order.id), "charge_id": charge.id}
        
    except User.DoesNotExist:
        return {"status": "failed", "error": "User not found."}
    except Product.DoesNotExist:
        return {"status": "failed", "error": "Product not found."}
