# Generated by Django 6.1 on 2026-08-16 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_photo_url',
            field=models.URLField(blank=True, help_text="URL to the user's profile picture.", null=True),
        ),
    ]
