# Generated by Django 6.1 on 2026-08-16 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_profile_photo_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='profile_photo_url',
        ),
        migrations.AddField(
            model_name='user',
            name='profile_photo',
            field=models.ImageField(blank=True, help_text="The user's profile picture.", null=True, upload_to='profiles/'),
        ),
    ]
