# Generated by Django 6.1 on 2026-08-30 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_user_profile_photo_url_user_profile_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_email_verified',
            field=models.BooleanField(default=False, help_text='Designates whether the user has verified their email address.'),
        ),
    ]
